### ISSUE TITLE
CakeProcessor.java 中 processingEnv不知道怎么来的

### ISSUE THREAD

**Issue by ityulong** [lizhaoxuan/Android-APT-Framework#3]
processingEnv并没有显示初始化过程，对于初学者来说告知init过程可能比较好理解

**Comment by lizhaoxuan** [comment]
这个问题比较尴尬，也是我一直认为模板模式的一个缺点，在父类中提供了一些方法或属性时，只靠阅读子类会感觉特别困惑，不知道这个方法或属性是哪里来的。
processingEnv是CakeProcessor的父类AbstractProcessor的一个protected属性，其初始化过程是在父类中完成的，子类可以直接使用。
不过还是在博客中说明一下的比较好，谢谢提醒啦，后面我去更新一下

**Comment by ityulong** [comment]
嗯 好的
